services:
  geoapp-converter:
    build: .
    image: christophe2bu/geoapp-converter:165c869e885
    volumes:
      - /opt/geoapp-util:/opt/geoapp-util
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
